import React, { Fragment } from 'react'
import { Container, Row, Col } from 'react-grid-system';
import { MDBIcon } from "mdbreact";
import './EditReport.css'
import Header from './Header'
const cssStyle = {
    fontweight5: {
        fontWeight: "500"
    }

};
class EditReports extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            fontWeight: "500"
        }

    }

    render() {
        return (
            <Container fluid>
                <Row style={{ marginTop: "37px" }}>
                    <Col sm={12}>
                        <Header />
                    </Col>
                </Row>
                <br></br>
                <Row style={{ background: "white", padding: "15px" }}>
                    <Col sm={12}>
                        <Row>
                            <Col sm={3}>
                                <div style={{ marginTop: "75px" }}>
                                    <h6><b>Tusday, 14/0120</b></h6>
                                    <h3><b style={{ fontWeight: "500" }}>SAFETY REPORT</b></h3>
                                </div>
                            </Col>
                            <Col sm={6}>
                            </Col>
                            <Col sm={3}>
                                <div style={{ textAlign: "right" }}>
                                    <h5 style={{ fontWeight: "500" }}><b>Report generated by</b></h5>
                                    <h5>Peter Tam</h5>
                                    <h5 style={{ fontWeight: "500" }}><b>Report generated by</b></h5>
                                    <h5>Peter Tam</h5>
                                    <h5 style={{ fontWeight: "500" }}><b>Report generated by</b></h5>
                                    <h5>Peter Tam</h5>
                                </div>


                            </Col>
                        </Row>
                        <hr></hr>
                        <p><h5 style={{ fontWeight: "500" }}><b>Unsatisfactory</b></h5></p>
                        <Row>
                            <Col sm={3}>
                                <label className="lbl">Offending Area</label>
                                <div style={{ height: "176px", background: "gray", borderRadius: "5px" }}>

                                </div>
                            </Col>
                            <Col sm={3}>
                                <br />
                                <label className="lbl">Person in charge</label>
                                <h5 style={{ fontWeight: "500" }}>Mary Chia</h5>
                                <br></br>
                                <label className="lbl">Description</label>
                                <button style={{ float: "right", border: '0px', background: "white" }}><MDBIcon icon="pen" /></button>
                                <p>
                                    <b>
                                        wertuioxcjk  swetuio dfghj kr tyyyy fjhdskf
                                        wertuioxcjk  swetuio dfghj

                                    </b>
                                </p>
                                <br></br>
                            </Col>
                            <Col sm={3}>
                                <label className="lbl">Rectified Situation</label>
                                <div style={{ height: "176px", background: "gray", borderRadius: "5px" }}>

                                </div>
                            </Col>
                            <Col sm={3}>
                                <br></br>
                                <h6 className="lbl">Date/Time</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>
                                <h6 className="lbl">Person in charge</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>
                                <h6 className="lbl">Person in charge</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>


                            </Col>
                        </Row>
                        <hr></hr>
                        <Row>
                            <Col sm={3}>
                                <label className="lbl">Offending Area</label>
                                <div style={{ height: "176px", background: "gray", borderRadius: "5px" }}>

                                </div>
                            </Col>
                            <Col sm={3}>
                                <br />
                                <label className="lbl">Person in charge</label>
                                <h5 style={cssStyle.fontweight5}>Mary Chia</h5>
                                <br></br>
                                <label className="lbl">Description</label>

                                <p>
                                    <b>
                                        wertuioxcjk  swetuio dfghj kr tyyyy fjhdskf
                                        wertuioxcjk  swetuio dfghj

                                    </b>
                                </p>
                                <br></br>
                            </Col>
                            <Col sm={3}>
                                <label className="lbl">Rectified Situation</label>
                                <div style={{ height: "176px", display: "flex", alignItems: "center", padding: "12px" }}>
                                    <div style={{
                                        border: "1px solid red",
                                        color: "red",
                                        padding: "10px",
                                        border: "1px solid red",
                                        paddingLeft: "23px",
                                        paddingRight: "23px",
                                        width: "100%",
                                        textAlign: "center"
                                    }}>
                                        UNRECTIFIRED
                                    </div>
                                </div>
                            </Col>
                            <Col sm={3}>
                                <br></br>
                                <h6 className="lbl">Date/Time</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>
                                <h6 className="lbl">Person in charge</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>
                                <h6 className="lbl">Person in charge</h6>
                                <label style={cssStyle.fontweight5}>Mary Chia</label>


                            </Col>
                        </Row>
                        <hr></hr>
                        <Row>
                            <Col sm={3}>
                                <label className="lbl">Offending Area</label>

                            </Col>
                            <Col sm={3}>

                            </Col>
                            <Col sm={3}>
                                <label className="lbl">Rectified Situation</label>

                            </Col>
                            <Col sm={3}>

                            </Col>
                        </Row>
                    </Col>
                </Row>

            </Container>
        )
    }
}
export default EditReports